services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: betting
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"   # DB-Port auf Host mappen, damit VSCode zugreifen kann

  app:
    build: .
    restart: always
    depends_on:
      - db   # nur Startreihenfolge, keine Healthchecks
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
